version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_DEEPAI_API_KEY=${VITE_DEEPAI_API_KEY}
      - VITE_ADMIN_EMAILS=${VITE_ADMIN_EMAILS}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge